### PR TITLE
Live demo (to be completed)

### PR DESCRIPTION
**Pull request by nthiery**
This adds a Dockerfile describing the software dependencies to enable trying the code online with Binder. Also adds a to-be-completed demo Jupyter notebook.

### CODE REVIEW

**Comment by nthiery** [comment]
TODO: update the URL in the README to point to the original repo; I left it temporarily to `nthiery` to make the link work before this PR gets merged.

**Comment by nthiery** [comment]
This is a follow up from the demo at FPSAC this morning.

**Review by LorenzoVenturello — APPROVED** [review]

**Comment by nthiery** [comment]
Cool! There remains for you to fix the binder link to point to your repo instead of mine. And of course finishing the demo notebook :-) Then I can announce your online demo tomorrow during the software session presentation.

**Comment by LorenzoVenturello** [comment]
Thanks for your help! I just added a couple of things to the README *brief description, links to the extended abstract and slides), and finished the demo notebook. Could you please take a look?

**Comment by nthiery** [comment]
> Thanks for your help! I just added a couple of things to the README
> *brief description, links to the extended abstract and slides), and
> finished the demo notebook. Could you please take a look?

Great. See PR. The demo looks good. I'll advertise the new online demo
tomorrow.

It made me wonder: would it be possible to visualize the initial
triangulation and the final triangulation? Maybe even to see the
intermediate steps using some interactive widget? It would be a nice
illustration of how the algorithm works.

Cheers,
		Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by LorenzoVenturello** [comment]
That's an interesting idea! Anyway we could not visualize all the cases considered, since most of them are not embeddable in R^3. But it would work for 2-dimensional spheres or orientable surfaces, even though it sounds rather complicated to implement.

**Pull request merged**
